version: "3.9"
services:
  web:
    build: .
    command: gunicorn private_diary.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
#       - .:/code
      - static_vol:/code/static
      - media_vol:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      
  nginx:
    build: ./nginx
    volumes:
      - static_vol:/usr/share/nginx/html/static
      - media_vol:/usr/share/nginx/html/media
    ports:
      - "80:80"
    depends_on:
    - web


  db:
    image: postgres
    volumes:
      - ./data/dbi5k:/var/lib/postgresql/data
    env_file: ./.env
    environment:
      - POSTGRES_DB=private_diary
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


volumes:
    static_vol:
    media_vol:
